---
- name: docker and docker-comp install with update cash
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: create directory for app
  file:
    path: /home/{{ ansible_ssh_user }}/myapp
    state: directory
    mode: '0755'

- name: docker-compose.yml on server
  copy:
    src: files/docker-compose.yml
    dest: /home/{{ ansible_ssh_user }}/myapp/docker-compose.yml

- name: ngnix conf file generate
  template:
    src: nginx.conf.j2
    dest: /home/{{ ansible_ssh_user }}/myapp/nginx.conf

- name: docker up
  docker_compose:
    project_src: /home/{{ ansible_ssh_user }}/myapp
    state: present

- name: ngnix up (restart)
  systemd:
    name: nginx
    state: restarted
    enabled: yes