version: '3'
services:
  web:
    build:
      context: ../php
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: effectiveMobilePass
      MYSQL_DATABASE: effectiveMobiledb